AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub Actions OIDC Provider and IAM Role for ECS Deployment'

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization or username
    Default: RYA234

  GitHubRepo:
    Type: String
    Description: GitHub repository name
    Default: dotnet_container

  ECSClusterName:
    Type: String
    Description: ECS Cluster name
    Default: app-cluster

  ECSServiceName:
    Type: String
    Description: ECS Service name
    Default: dotnet-service

Resources:
  # IAM Role for GitHub Actions (using existing OIDC Provider)
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubActionsRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${GitHubRepo}:*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      Policies:
        - PolicyName: ECSDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:DescribeServices
                  - ecs:DescribeTaskDefinition
                  - ecs:DescribeTasks
                  - ecs:ListTasks
                  - ecs:RegisterTaskDefinition
                  - ecs:UpdateService
                  - ecs:DescribeClusters
                Resource: '*'
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/ecs-task-execution-role
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/ecs-task-role
                Condition:
                  StringLike:
                    iam:PassedToService: ecs-tasks.amazonaws.com

Outputs:
  GitHubActionsRoleArn:
    Description: ARN of the GitHub Actions IAM Role
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: GitHubActionsRoleArn

  OIDCProviderArn:
    Description: ARN of the existing GitHub OIDC Provider
    Value: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
