name: 🏗️ Infrastructure
description: Infrastructure, deployment, or DevOps related
title: "[INFRA] "
labels: ["deployment", "priority:medium"]
body:
  - type: markdown
    attributes:
      value: |
        Infrastructure and deployment related issues
        
  - type: dropdown
    id: infra_type
    attributes:
      label: Infrastructure Type
      description: What kind of infrastructure work?
      options:
        - AWS (ECS, ECR, ALB, etc.)
        - Docker / Containerization
        - CI/CD (GitHub Actions)
        - Monitoring / Logging
        - Security / IAM
        - Database
        - Networking
        - Cost Optimization
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this?
      options:
        - High (Blocking deployment)
        - Medium (Should be done soon)
        - Low (Nice to have)
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What infrastructure work needs to be done?
      placeholder: Describe the infrastructure task
    validations:
      required: true
      
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this needed?
      placeholder: What problem does this solve?
    validations:
      required: true
      
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: List of tasks to complete
      placeholder: |
        - [ ] Update Terraform
        - [ ] Test in staging
        - [ ] Deploy to production
        - [ ] Update documentation
    validations:
      required: true
      
  - type: textarea
    id: risks
    attributes:
      label: Risks / Considerations
      description: Any potential risks or things to consider?
      placeholder: |
        - Downtime required?
        - Data migration needed?
        - Cost impact?
        
  - type: textarea
    id: rollback
    attributes:
      label: Rollback Plan
      description: How can we rollback if something goes wrong?
      placeholder: Describe the rollback procedure
      
  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to Terraform code, AWS docs, etc.
      placeholder: |
        - Terraform: my_web_infra/Terraform/aws/
        - AWS Doc: https://docs.aws.amazon.com/...
