-- N+1問題デモ用のダミーデータInsert文

-- 部署データ（10部署）
INSERT INTO Departments (Name) VALUES
    (N'開発部'),
    (N'営業部'),
    (N'人事部'),
    (N'総務部'),
    (N'マーケティング部'),
    (N'経理部'),
    (N'法務部'),
    (N'カスタマーサポート部'),
    (N'企画部'),
    (N'品質保証部');

-- ユーザーデータ（100人）
INSERT INTO Users (Name, DepartmentId, Email) VALUES
    (N'山田太郎', 1, 'yamada.taro@example.com'),
    (N'佐藤花子', 2, 'sato.hanako@example.com'),
    (N'鈴木一郎', 1, 'suzuki.ichiro@example.com'),
    (N'高橋美咲', 3, 'takahashi.misaki@example.com'),
    (N'田中健太', 1, 'tanaka.kenta@example.com'),
    (N'伊藤愛', 4, 'ito.ai@example.com'),
    (N'渡辺翔', 2, 'watanabe.sho@example.com'),
    (N'中村結衣', 5, 'nakamura.yui@example.com'),
    (N'小林大輔', 1, 'kobayashi.daisuke@example.com'),
    (N'加藤さくら', 6, 'kato.sakura@example.com'),
    (N'吉田拓海', 2, 'yoshida.takumi@example.com'),
    (N'山本陽菜', 7, 'yamamoto.haruna@example.com'),
    (N'佐々木蓮', 1, 'sasaki.ren@example.com'),
    (N'松本葵', 3, 'matsumoto.aoi@example.com'),
    (N'井上悠', 8, 'inoue.yu@example.com'),
    (N'木村凛', 2, 'kimura.rin@example.com'),
    (N'林大和', 1, 'hayashi.yamato@example.com'),
    (N'斎藤ひまわり', 4, 'saito.himawari@example.com'),
    (N'清水颯', 9, 'shimizu.hayate@example.com'),
    (N'山口咲希', 1, 'yamaguchi.saki@example.com'),
    (N'森田悠斗', 5, 'morita.yuto@example.com'),
    (N'阿部莉子', 2, 'abe.riko@example.com'),
    (N'池田陸', 10, 'ikeda.riku@example.com'),
    (N'橋本美羽', 1, 'hashimoto.miu@example.com'),
    (N'山崎蒼', 6, 'yamazaki.ao@example.com'),
    (N'石川心春', 3, 'ishikawa.koharu@example.com'),
    (N'前田晴', 7, 'maeda.haru@example.com'),
    (N'岡田陽', 1, 'okada.haru@example.com'),
    (N'長谷川楓', 2, 'hasegawa.kaede@example.com'),
    (N'後藤輝', 8, 'goto.hikaru@example.com'),
    (N'藤田空', 4, 'fujita.sora@example.com'),
    (N'村上明', 1, 'murakami.akira@example.com'),
    (N'近藤美月', 9, 'kondo.mizuki@example.com'),
    (N'遠藤隼', 5, 'endo.hayato@example.com'),
    (N'青木七海', 2, 'aoki.nanami@example.com'),
    (N'坂本龍', 1, 'sakamoto.ryu@example.com'),
    (N'西村星', 10, 'nishimura.hoshi@example.com'),
    (N'福田海', 3, 'fukuda.kai@example.com'),
    (N'太田桜', 6, 'ota.sakura@example.com'),
    (N'三浦翼', 1, 'miura.tsubasa@example.com'),
    (N'藤井光', 7, 'fujii.hikari@example.com'),
    (N'岡本優', 2, 'okamoto.yu@example.com'),
    (N'松田湊', 4, 'matsuda.minato@example.com'),
    (N'竹内澪', 1, 'takeuchi.mio@example.com'),
    (N'中島紬', 8, 'nakajima.tsumugi@example.com'),
    (N'金子樹', 5, 'kaneko.itsuki@example.com'),
    (N'藤原詩', 9, 'fujiwara.uta@example.com'),
    (N'原田結', 2, 'harada.yui@example.com'),
    (N'杉山颯太', 1, 'sugiyama.sota@example.com'),
    (N'小川心', 3, 'ogawa.kokoro@example.com'),
    (N'谷口日向', 10, 'taniguchi.hinata@example.com'),
    (N'今井朝陽', 6, 'imai.asahi@example.com'),
    (N'河野奏', 1, 'kono.kanade@example.com'),
    (N'古川颯希', 7, 'furukawa.satsuki@example.com'),
    (N'石田葉月', 4, 'ishida.hazuki@example.com'),
    (N'上田碧', 2, 'ueda.aoi@example.com'),
    (N'森光', 8, 'mori.hikaru@example.com'),
    (N'柴田和', 1, 'shibata.nagomi@example.com'),
    (N'横山遥', 5, 'yokoyama.haruka@example.com'),
    (N'宮崎瑠', 9, 'miyazaki.ruru@example.com'),
    (N'内田羽', 3, 'uchida.tsubasa@example.com'),
    (N'高田海斗', 1, 'takada.kaito@example.com'),
    (N'安藤美空', 2, 'ando.misora@example.com'),
    (N'島田颯', 10, 'shimada.hayate@example.com'),
    (N'谷結菜', 6, 'tani.yuina@example.com'),
    (N'大野陽翔', 4, 'ono.haruto@example.com'),
    (N'平野陽葵', 1, 'hirano.himari@example.com'),
    (N'久保琉生', 7, 'kubo.ryuki@example.com'),
    (N'野村桃花', 3, 'nomura.momoka@example.com'),
    (N'酒井蒼空', 8, 'sakai.sora@example.com'),
    (N'市川芽依', 2, 'ichikawa.mei@example.com'),
    (N'増田陸翔', 5, 'masuda.rikuto@example.com'),
    (N'永井紗良', 1, 'nagai.sara@example.com'),
    (N'大西悠真', 9, 'onishi.yuma@example.com'),
    (N'菅原心結', 4, 'sugawara.miyu@example.com'),
    (N'和田碧斗', 10, 'wada.aoto@example.com'),
    (N'大塚莉央', 6, 'otsuka.rio@example.com'),
    (N'千葉凪', 2, 'chiba.nagi@example.com'),
    (N'田村悠月', 1, 'tamura.yuzuki@example.com'),
    (N'岩崎陽向', 3, 'iwasaki.hinata@example.com'),
    (N'中野一花', 7, 'nakano.ichika@example.com'),
    (N'堀翔真', 8, 'hori.shoma@example.com'),
    (N'小野寺優奈', 5, 'onodera.yuna@example.com'),
    (N'菊地蓮斗', 1, 'kikuchi.rento@example.com'),
    (N'宮本心春', 4, 'miyamoto.koharu@example.com'),
    (N'新井大智', 9, 'arai.daichi@example.com'),
    (N'沢田花音', 2, 'sawada.kanon@example.com'),
    (N'北村悠人', 10, 'kitamura.yuto@example.com'),
    (N'関口彩乃', 6, 'sekiguchi.ayano@example.com'),
    (N'東優希', 3, 'azuma.yuki@example.com'),
    (N'須藤碧海', 1, 'sudo.aomi@example.com'),
    (N'片岡陽太', 7, 'kataoka.yota@example.com'),
    (N'工藤心音', 8, 'kudo.kokone@example.com'),
    (N'白石結愛', 5, 'shiraishi.yua@example.com'),
    (N'星野颯希', 4, 'hoshino.satsuki@example.com'),
    (N'上野陽菜乃', 2, 'ueno.hinano@example.com'),
    (N'丸山湊斗', 9, 'maruyama.minato@example.com'),
    (N'松岡心晴', 1, 'matsuoka.koharu@example.com'),
    (N'川口陸斗', 10, 'kawaguchi.rikuto@example.com');
